### PR TITLE
Added Copy Filestore ticket/password to Clipboard feature to profile page

### PR DESCRIPTION
**Pull request by susheel**
Not tested this as this is a quick hack.

### CODE REVIEW

**Comment by susheel** [comment]
@asaglimbeni Could you test the zeroclipboard feature? I haven't tested it at all

**Comment by asaglimbeni** [comment]
Sorry susheel , but it seems doen't work this commit :(

**Comment by susheel** [comment]
I suspect it's the zeroclipboard bit. Could you look at it? I just don't know how to fix it!! :(

**Comment by asaglimbeni** [comment]
here the fix https://github.com/b3c/vphshare/commit/ca0756267ada9417c075d95fa4dbb82ca25319c2
available in the develop instance . 
Bye

**Pull request merged**
