### PR TITLE
cloud views update

### PR DESCRIPTION
**Pull request by dharezlak**
- minor UI updates
- cloud views can now handle asynchronous instance initialization

### CODE REVIEW

**Comment by dharezlak** [comment]
Let me know when this will be available in the production instance.

**Comment by mkarmona** [comment]
It's ready into the develop instance.

**Comment by dharezlak** [comment]
OK, it works well. Please, proceed with production deployment whenever you feel ready.

**Comment by mkarmona** [comment]
merged and deployed.

**Pull request merged**
